/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as SyncUserApiImport } from './routes/syncUser.api'
import { Route as SignupVerificationStepImport } from './routes/signup.$verificationStep'
import { Route as LoginVerificationStepImport } from './routes/login.$verificationStep'
import { Route as AuthedPostsRouteImport } from './routes/_authed/posts.route'
import { Route as AuthedPostsIndexImport } from './routes/_authed/posts.index'
import { Route as AuthedUsersApiImport } from './routes/_authed/users.api'
import { Route as AuthedSetadminApiImport } from './routes/_authed/setadmin.api'
import { Route as AuthedPostsPostIdImport } from './routes/_authed/posts.$postId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SyncUserApiRoute = SyncUserApiImport.update({
  id: '/syncUser/api',
  path: '/syncUser/api',
  getParentRoute: () => rootRoute,
} as any)

const SignupVerificationStepRoute = SignupVerificationStepImport.update({
  id: '/$verificationStep',
  path: '/$verificationStep',
  getParentRoute: () => SignupRoute,
} as any)

const LoginVerificationStepRoute = LoginVerificationStepImport.update({
  id: '/$verificationStep',
  path: '/$verificationStep',
  getParentRoute: () => LoginRoute,
} as any)

const AuthedPostsRouteRoute = AuthedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedPostsIndexRoute = AuthedPostsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPostsRouteRoute,
} as any)

const AuthedUsersApiRoute = AuthedUsersApiImport.update({
  id: '/users/api',
  path: '/users/api',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedSetadminApiRoute = AuthedSetadminApiImport.update({
  id: '/setadmin/api',
  path: '/setadmin/api',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedPostsPostIdRoute = AuthedPostsPostIdImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AuthedPostsRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_authed/posts': {
      id: '/_authed/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthedPostsRouteImport
      parentRoute: typeof AuthedImport
    }
    '/login/$verificationStep': {
      id: '/login/$verificationStep'
      path: '/$verificationStep'
      fullPath: '/login/$verificationStep'
      preLoaderRoute: typeof LoginVerificationStepImport
      parentRoute: typeof LoginImport
    }
    '/signup/$verificationStep': {
      id: '/signup/$verificationStep'
      path: '/$verificationStep'
      fullPath: '/signup/$verificationStep'
      preLoaderRoute: typeof SignupVerificationStepImport
      parentRoute: typeof SignupImport
    }
    '/syncUser/api': {
      id: '/syncUser/api'
      path: '/syncUser/api'
      fullPath: '/syncUser/api'
      preLoaderRoute: typeof SyncUserApiImport
      parentRoute: typeof rootRoute
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdImport
      parentRoute: typeof AuthedPostsRouteImport
    }
    '/_authed/setadmin/api': {
      id: '/_authed/setadmin/api'
      path: '/setadmin/api'
      fullPath: '/setadmin/api'
      preLoaderRoute: typeof AuthedSetadminApiImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/users/api': {
      id: '/_authed/users/api'
      path: '/users/api'
      fullPath: '/users/api'
      preLoaderRoute: typeof AuthedUsersApiImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexImport
      parentRoute: typeof AuthedPostsRouteImport
    }
  }
}

// Create and export the route tree

interface AuthedPostsRouteRouteChildren {
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedPostsRouteRouteChildren: AuthedPostsRouteRouteChildren = {
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedPostsRouteRouteWithChildren =
  AuthedPostsRouteRoute._addFileChildren(AuthedPostsRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedPostsRouteRoute: typeof AuthedPostsRouteRouteWithChildren
  AuthedSetadminApiRoute: typeof AuthedSetadminApiRoute
  AuthedUsersApiRoute: typeof AuthedUsersApiRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedPostsRouteRoute: AuthedPostsRouteRouteWithChildren,
  AuthedSetadminApiRoute: AuthedSetadminApiRoute,
  AuthedUsersApiRoute: AuthedUsersApiRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface LoginRouteChildren {
  LoginVerificationStepRoute: typeof LoginVerificationStepRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginVerificationStepRoute: LoginVerificationStepRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface SignupRouteChildren {
  SignupVerificationStepRoute: typeof SignupVerificationStepRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupVerificationStepRoute: SignupVerificationStepRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ProtectedRoute
  '/login': typeof LoginRouteWithChildren
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRouteWithChildren
  '/posts': typeof AuthedPostsRouteRouteWithChildren
  '/login/$verificationStep': typeof LoginVerificationStepRoute
  '/signup/$verificationStep': typeof SignupVerificationStepRoute
  '/syncUser/api': typeof SyncUserApiRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/setadmin/api': typeof AuthedSetadminApiRoute
  '/users/api': typeof AuthedUsersApiRoute
  '/posts/': typeof AuthedPostsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ProtectedRoute
  '/login': typeof LoginRouteWithChildren
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRouteWithChildren
  '/login/$verificationStep': typeof LoginVerificationStepRoute
  '/signup/$verificationStep': typeof SignupVerificationStepRoute
  '/syncUser/api': typeof SyncUserApiRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/setadmin/api': typeof AuthedSetadminApiRoute
  '/users/api': typeof AuthedUsersApiRoute
  '/posts': typeof AuthedPostsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_protected': typeof ProtectedRoute
  '/login': typeof LoginRouteWithChildren
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRouteWithChildren
  '/_authed/posts': typeof AuthedPostsRouteRouteWithChildren
  '/login/$verificationStep': typeof LoginVerificationStepRoute
  '/signup/$verificationStep': typeof SignupVerificationStepRoute
  '/syncUser/api': typeof SyncUserApiRoute
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/_authed/setadmin/api': typeof AuthedSetadminApiRoute
  '/_authed/users/api': typeof AuthedUsersApiRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/logout'
    | '/signup'
    | '/posts'
    | '/login/$verificationStep'
    | '/signup/$verificationStep'
    | '/syncUser/api'
    | '/posts/$postId'
    | '/setadmin/api'
    | '/users/api'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/logout'
    | '/signup'
    | '/login/$verificationStep'
    | '/signup/$verificationStep'
    | '/syncUser/api'
    | '/posts/$postId'
    | '/setadmin/api'
    | '/users/api'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_protected'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/posts'
    | '/login/$verificationStep'
    | '/signup/$verificationStep'
    | '/syncUser/api'
    | '/_authed/posts/$postId'
    | '/_authed/setadmin/api'
    | '/_authed/users/api'
    | '/_authed/posts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ProtectedRoute: typeof ProtectedRoute
  LoginRoute: typeof LoginRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRouteWithChildren
  SyncUserApiRoute: typeof SyncUserApiRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ProtectedRoute: ProtectedRoute,
  LoginRoute: LoginRouteWithChildren,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRouteWithChildren,
  SyncUserApiRoute: SyncUserApiRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed",
        "/_protected",
        "/login",
        "/logout",
        "/signup",
        "/syncUser/api"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/posts",
        "/_authed/setadmin/api",
        "/_authed/users/api"
      ]
    },
    "/_protected": {
      "filePath": "_protected.tsx"
    },
    "/login": {
      "filePath": "login.tsx",
      "children": [
        "/login/$verificationStep"
      ]
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx",
      "children": [
        "/signup/$verificationStep"
      ]
    },
    "/_authed/posts": {
      "filePath": "_authed/posts.route.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/posts/$postId",
        "/_authed/posts/"
      ]
    },
    "/login/$verificationStep": {
      "filePath": "login.$verificationStep.tsx",
      "parent": "/login"
    },
    "/signup/$verificationStep": {
      "filePath": "signup.$verificationStep.tsx",
      "parent": "/signup"
    },
    "/syncUser/api": {
      "filePath": "syncUser.api.ts"
    },
    "/_authed/posts/$postId": {
      "filePath": "_authed/posts.$postId.tsx",
      "parent": "/_authed/posts"
    },
    "/_authed/setadmin/api": {
      "filePath": "_authed/setadmin.api.ts",
      "parent": "/_authed"
    },
    "/_authed/users/api": {
      "filePath": "_authed/users.api.ts",
      "parent": "/_authed"
    },
    "/_authed/posts/": {
      "filePath": "_authed/posts.index.tsx",
      "parent": "/_authed/posts"
    }
  }
}
ROUTE_MANIFEST_END */
